micronaut:
  application:
    name: demo
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
netty:
  default:
    allocator:
      max-order: 3
bluemedia:
  service-id: ${BM_SERVICE_ID}
  shared-key: ${BM_SHARED_KEY}
  gateway-url: ${BM_GATEWAY_URL}
