micronaut:
  application:
    name: example
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
netty:
  default:
    allocator:
      max-order: 3
