micronaut:
  application:
    name: demo
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
  server:
    netty:
      access-logger:
        enabled: true
        log-format: common
netty:
  default:
    allocator:
      max-order: 3
autopay:
  service-id: ${AUTOPAY_SERVICE_ID}
  shared-key: ${AUTOPAY_SHARED_KEY}
  gateway-url: ${AUTOPAY_GATEWAY_URL}
  itn-endpoint: ${AUTOPAY_ITN_ENDPOINT}
