package krystian.kryszczak.bm.sdk.util;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class RandomUtilsTest {

    @Test
    public void randomMessageIdMultipleTest() {
        // TODO check if in PHP length of random generated bytes instance of string have always length equals MESSAGE_ID_LENGTH
        for (int i = 0; i < 1000; i++) {
            assertEquals(32, RandomUtils.randomMessageId().length());
        }
    }
}
